# Makefile.wat -- Build EDITCOL.DLL and TEST.EXE with Open Watcom 2.0
# Run from the project root: wmake -f Makefile.wat 2>&1 | tee compile.log
#
# Output:
#   dll\EDITCOL.DLL      rebuilt DLL
#   lib\EDITCOL.LIB      import library (auto-generated by wlink)
#   sample\TEST.EXE      test application

CC = wcc386

CFLAGS_DLL = -bt=os2 -bm -bd -5 -fpi -Oaxt -W3 -Isrc -Ih
CFLAGS_EXE = -bt=os2 -bm -5 -fpi -Oaxt -W3 -Ih

all: dll\EDITCOL.DLL sample\TEST.EXE

# -------------------------------------------------------------------
# EDITCOL.DLL
# -------------------------------------------------------------------
dll\EDITCOL.DLL: src\editcol.obj src\editcol.res
	wlink system os2v2_dll initinstance name dll\EDITCOL.DLL &
	    file src\editcol.obj &
	    export WinEditColorDlg.1 &
	    option implib=lib\EDITCOL.LIB &
	    option map=dll\EDITCOL.MAP
	wrc -q src\editcol.res dll\EDITCOL.DLL

src\editcol.obj: src\editcol.c h\editcol.h
	$(CC) $(CFLAGS_DLL) -fo=src\editcol.obj src\editcol.c

src\editcol.res: src\editcol.rc h\editcol.h
	wrc -r -Isrc -Ih -fo=src\editcol.res src\editcol.rc

# -------------------------------------------------------------------
# TEST.EXE
# Depends on lib\EDITCOL.LIB produced by the DLL step above
# -------------------------------------------------------------------
sample\TEST.EXE: sample\test.obj sample\test.res dll\EDITCOL.DLL
	wlink system os2v2_pm name sample\TEST.EXE &
	    file sample\test.obj &
	    lib lib\EDITCOL.LIB &
	    option stack=65536 &
	    option map=sample\TEST.MAP
	wrc -q sample\test.res sample\TEST.EXE

sample\test.obj: sample\test.c h\editcol.h
	$(CC) $(CFLAGS_EXE) -fo=sample\test.obj sample\test.c

sample\test.res: sample\test.rc sample\test.ICO
	wrc -r -Isample -fo=sample\test.res sample\test.rc

# -------------------------------------------------------------------
clean: .symbolic
	@if exist src\editcol.obj    del src\editcol.obj
	@if exist src\editcol.res    del src\editcol.res
	@if exist sample\test.obj    del sample\test.obj
	@if exist sample\test.res    del sample\test.res
	@if exist dll\EDITCOL.DLL    del dll\EDITCOL.DLL
	@if exist dll\EDITCOL.MAP    del dll\EDITCOL.MAP
	@if exist lib\EDITCOL.LIB    del lib\EDITCOL.LIB
	@if exist sample\TEST.EXE    del sample\TEST.EXE
	@if exist sample\TEST.MAP    del sample\TEST.MAP
	@if exist compile.log        del compile.log
